name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 3. Build the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: ./Dockerfile
          tags: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/payload-web-sample:latest
          push: false   # Build first without pushing

      # 4. Verify login worked and image exists
      - name: Verify Docker login
        run: |
          docker info
          docker images

      # 5. Push the image
      - name: Push Docker image
        run: |
          docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/payload-web-sample:latest
